// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFW7G0eYR4m1zAHAPYNMqH12dDNDrUvJ4',
    appId: '1:485979816391:web:9225fc20d6e779d8fad9e2',
    messagingSenderId: '485979816391',
    projectId: 'machine-test-chennai',
    authDomain: 'machine-test-chennai.firebaseapp.com',
    storageBucket: 'machine-test-chennai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNx9mVjHPrbmzcPILNUdmUOmUilgjip6Q',
    appId: '1:485979816391:android:f041de56d902874cfad9e2',
    messagingSenderId: '485979816391',
    projectId: 'machine-test-chennai',
    storageBucket: 'machine-test-chennai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYTsfSn6EpwZ1876zgg0Sgh6J-_yVMt6A',
    appId: '1:485979816391:ios:11db5ad6bae6230bfad9e2',
    messagingSenderId: '485979816391',
    projectId: 'machine-test-chennai',
    storageBucket: 'machine-test-chennai.appspot.com',
    iosClientId: '485979816391-f0se690ciiog7bjd0dnmnd0qrslr4srt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chennaiMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYTsfSn6EpwZ1876zgg0Sgh6J-_yVMt6A',
    appId: '1:485979816391:ios:11db5ad6bae6230bfad9e2',
    messagingSenderId: '485979816391',
    projectId: 'machine-test-chennai',
    storageBucket: 'machine-test-chennai.appspot.com',
    iosClientId: '485979816391-f0se690ciiog7bjd0dnmnd0qrslr4srt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chennaiMachineTest',
  );
}
